Jump feature
belivvr/career.belivvr.com pull request #48
Opened 2022-07-08 05:45 UTC by jeus0630

## Doing
- 점프 기능 추가

2022-07-08 06:46 UTC, juunini requested changes

2022-07-08 06:46 UTC, juunini commented on src/aframe/jump.js
> +    window.addEventListener('keydown', (e) => this.keydownHanlder(e));
```suggestion
    window.addEventListener('keydown', this.keydownHanlder);
```

2022-07-08 06:46 UTC, juunini commented on src/aframe/jump.js
> +    const jumpUpAnimation = setInterval(() => {
https://developer.mozilla.org/ko/docs/Web/API/Window/requestAnimationFrame

setInterval을 쓰는게 아니라 requestAnimationFrame 이라는 API가 있어요.

2022-07-08 06:46 UTC, juunini commented on src/aframe/jump.js
> +    jumpVelocity: 0.002,
중력가속도 0.98...
내가 중력 엔진을 만든다 생각하고 한번 데이터를 찾아보세요.

저 예전에 궁금해서 중력 엔진 간단하게 직접 만들어본적 있는데
중력가속도를 써야만 했어요.
최대 자유낙하 속도도 있었어요

2022-07-08 06:47 UTC, juunini commented on src/aframe/jump.js
> +    jumpVelocity: 0.002,
js 중력 구현

이라고 검색하면 여러 정보를 얻으실  수 있을거에요

2022-07-08 06:48 UTC, jeus0630 commented on src/aframe/jump.js
> +    const jumpUpAnimation = setInterval(() => {
근데 그게 aframe registercomponent 안에서가 안되요 ㅜㅜ
그래서 저거 썻어요

2022-07-11 02:36 UTC, jeus0630 reviewed
와 깔끔하네요. 많이 배웠습니다👍🏼

2022-07-11 02:51 UTC, merged