Chat 기능 제작
belivvr/career.belivvr.com pull request #6
Opened 2022-06-28 06:11 UTC by jeus0630

##DOING

- Socket.io-client 사용
- 전에 보낸 메세지도 남아있게 하기 위해 State Management 인 Recoil 사용
- 서버에 보내는 API는 .env에 저장

2022-06-28 06:29 UTC, juunini commented on .vscode/settings.json
> +}
indent!!!

2022-06-28 06:29 UTC, juunini commented on package.json
> +    "recoil": "^0.7.4",
아니 리코일녀석 아직 v1 이 안됐었군 ㄷㄷ

2022-06-28 06:29 UTC, juunini commented on src/App.tsx
> +import chatState from './state/chat';
import 할 때 로컬 모듈은 한 줄 거리를 벌려서 구분해주는게 좋습니다

2022-06-28 06:29 UTC, juunini commented on src/App.tsx
> +  };
form 으로 받고 e.preventDefault 를 헀다면 state를 안쓰고도 가능해요

https://stackoverflow.com/questions/23427384/get-form-data-in-reactjs/59961329#59961329

![image](https://user-images.githubusercontent.com/41536271/176108479-5d51252d-4071-4a88-8dcd-62da4077cce0.png)

2022-06-28 06:29 UTC, juunini commented on src/App.tsx
> +  const [chats, setChats] = useRecoilState(chatState);
chat은 recoil을 안쓰고 useState 선에서 처리가 가능하죠

2022-06-29 02:16 UTC, juunini commented
![Screenshot_20220629-111617_Chrome](https://user-images.githubusercontent.com/41536271/176336787-1bae3231-9cf5-4a31-8d7a-27be2793a188.jpg)

병합

2022-06-29 02:19 UTC, juunini requested changes

2022-06-29 02:19 UTC, juunini commented on src/App.tsx
> +    for(let [, value] of formData.entries()){
entries().forEach(...

2022-06-29 02:19 UTC, juunini commented on src/App.tsx
> +          chats.map((chat,idx) => <li key={idx}>{chat}</li>)
idx
줄임말 금지

2022-06-29 02:19 UTC, juunini commented on src/App.tsx
> +        <input type="submit" value="Submit" />
submit은 왠만하면 버튼으로 구현하세요

2022-06-29 02:36 UTC, jeus0630 commented on src/App.tsx
> +    for(let [, value] of formData.entries()){
formData.entries()가 iterator 객체라서 forEach 쓰려면 Array.from()으로 Array로 바꿔줘야 되는데 그렇게 할까요?

2022-06-29 02:50 UTC, jeus0630 commented on src/App.tsx
> +    for(let [, value] of formData.entries()){
```
Array.from(formData.entries()).forEach(([,value]) => socket.emit('chat',value));
```

이렇게 가야해요

2022-06-29 05:10 UTC, juunini requested changes

2022-06-29 05:10 UTC, juunini commented on src/App.tsx
> +  const socket = io(import.meta.env.VITE_API_URL);
아 맞다 소켓생성을 함수 안에서 하면 계속 생성합니다. 소켓 밖에서 하거나 useEffect 안에서 해야해요

2022-06-29 05:16 UTC, jeus0630 commented on src/App.tsx
> +  const socket = io(import.meta.env.VITE_API_URL);
넵 밖으로 뺄게요

2022-06-29 05:16 UTC, jeus0630 commented on src/App.tsx
> +    for(let [, value] of formData.entries()){
@juunini

2022-06-29 05:26 UTC, juunini commented on src/App.tsx
> +    for(let [, value] of formData.entries()){
formData.values().forEach

2022-06-29 05:43 UTC, juunini approved these changes
머지되고나서 현님이랑 채팅 메시지 타입 다시 논의해주세요.
id, name, message
이렇게 세 가지를 받아야 할 것 같아요

2022-06-29 05:43 UTC, merged